name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-deny,cargo-machete,dprint,typos-cli,ripgrep,shellcheck,shfmt
      - run: cargo install cargo-lintmax
      - run: cargo lintmax check
